### ISSUE TITLE
Cross compiling issue when enable cgo

### ISSUE THREAD

**Issue by jinzihuang** [ibmdb/go_ibm_db#15]
Hi team,

When i try to run go build in Travis. 

I am receiving this error:

github.com/ibmdb/go_ibm_db/api

../../../../../pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:13:9: undefined: SQLSMALLINT
../../../../../pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:14:9: undefined: SQLUSMALLINT
../../../../../pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:15:9: undefined: SQLUSMALLINT

Seems api.go was used instead of api_unix.go.
Any idea how to fix this?

Thank you!

**Comment by jinzihuang** [comment]
Seems it's a cross compiling problem
when we run
code:
```
export DB2HOME=gopath/src/github.com/ibmdb/go_ibm_db/installer/clidriver && \
export CGO_CFLAGS=-I${DB2HOME}/include && \
export CGO_LDFLAGS=-L${DB2HOME}/lib && \
export LD_LIBRARY_PATH=/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib && \
CGO_ENABLED=0 go build -a -o ./dist/query-linux
```

we got the following error
```
# github.com/ibmdb/go_ibm_db/api
../../../../../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:13:9: undefined: SQLSMALLINT
../../../../../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:14:9: undefined: SQLUSMALLINT
../../../../../../go/pkg/mod/github.com/ibmdb/go_ibm_db@v0.0.0-20190401124318-6c640a02c8b9/api/api.go:15:9: undefined: SQLUSMALLINT

```

**Comment by akhilravuri1** [comment]
Hi,

Why were you using CGO_ENABLED=0 before go build?

**Comment by jinzihuang** [comment]
Hi Akhil,
The way we build our project is we pulled all libraries/packages as binary, so that the docker container size will stay small.  
In order to do so we need to disable cgo. CGO_ENABLED=0, without cgo disabled the docker container binary crashed whenever we try to access to it.

**Comment by smuda** [comment]
@jinzihuang 
(I'm not a maintainer of this project)
Since this is a cgo project, you need to enable cgo. If you think about it, it's pretty natural since this project is just a shim on top of the IBM driver, which is a C level driver. To be able to talk to the C driver it will compile against the header files but to be able to do that, cgo must be enabled.

I suppose you're trying to create a docker image from scratch with just the (statically compiled) binary. There are a number of things to handle in that case, which is out of scope for this library.

Read the following article for reference. There are even more things to do, which includes handling the clib. Good luck!

https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671

**Comment by akhilravuri1** [comment]
Hi @jinzihuang 
As smuda said our driver internally uses cgo, If you disable cgo you cannot use our driver in Unix.

**Comment by jinzih** [comment]
Hi guys. 

We decided to do 2-stage docker builds in order to use go_ibm_db and make sure our container size is small.

The first step is to build the project in docker container. But I am facing an issue of installing go_ibm_db.

I am able to `download go_ibm_db`, install clidriver`, and set the needed `environment variables`.

But when come to install all it with other packages `go get ./...`

I ran into a problem:
```# github.com/ibmdb/go_ibm_db/api
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libcrypt.so.1, needed by /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libdl.so.2, needed by /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so, not found (try using -rpath or -rpath-link)
....
...
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so: undefined reference to `getgrgid_r@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so: undefined reference to `rand_r@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /go/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib/libdb2.so: undefined reference to `stdout@GLIBC_2.2.5'
collect2: error: ld returned 1 exit status
```


In my dockerfile, i following libs installed
```&& apk upgrade \
&& apk add openssl make git gcc g++ \
&& apk --no-cache add ca-certificates wget \
&& wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
&& wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk \
&& apk add glibc-2.25-r0.apk
```

Do I miss anything?

**Comment by akhilravuri1** [comment]
Hi @jinzih 

Ques:-But when come to install all it with other packages go get ./...


Our go_ibm_db drivers use cli driver files. 
1)
If you use go get the go compile after downloading the driver will compile the code and create the binary while compiling the code it will be unable to find the c include files beacuse they are present in the clidriver which we are going to download it in the next step (github readme process). 

2) 
So use go get -d github.com/ibmdb/go_ibm_db to download the driver in non-windows.

3)
To manage the process like installing the clidriver before compiling the driver code is not possible because the Go team did not give us access to manage the process of go get.

Thanks.

**Comment by akhilravuri1** [comment]
Hi @jinzih 

From the error, I see that libcrypt.so.1 and libdl.so.2 files are missing in your os so download those 2 files and it solves your issue. 

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Closing the issue as there is no reply from the customer from 12 days.

**Comment by Shah-Aayush** [comment]
I was able to resolve the issue by installing gcc (`apt install gcc`)
---
I was getting this error : 
`ibmdb/go_ibm_db/api/api.go:14:9: undefined: SQLSMALLINT`
