### ISSUE TITLE
Correct usage of pooling with go_ibm_db

### ISSUE THREAD

**Issue by kushaal-veijay** [ibmdb/go_ibm_db#158]
I am using the go_ibm_db, in my project where we are making lots of connection to the database. To avoid the cost of opening and closing the connection, we planned to use pool. We have created a pool size of 100. I have tried couple of approaches and wanted to understand what is the correct way.

Approach 1: Whenever we need to query the database, we take the connection from the Pool using pool.Open and when the work is done, we do DBP.Close() to release the connection back to the pool. However, we observe that if the number of calls increase the the number of go routines responsible for timeout increases tremendously. Attaching the snap for pprof tool

```
goroutine profile: total 13699
13676 @ 0x43b576 0x409b2c 0x409558 0x7a9a76 0x46b861
#	0x7a9a75	github.ibm.com/sec-ci/abac-compute/internal/db2.(*DBP).Timeout+0x35
```

Approach 2: Whenever we need to query the database, we take the connection from the Pool using pool.Open and do not close it afterwards. However, in this case I donot see go routine for (*DBP).Timeout, but I do see go routines for database/sql.(*DB).connectionOpener increasing with every call to database. Attaching the snap from pprof

```
goroutine profile: total 1055
933 @ 0x43b576 0x44b1d2 0x7790b3 0x46b861
#	0x7790b2	database/sql.(*DB).connectionOpener+0x92	/usr/local/go/src/database/sql/sql.go:1196

100 @ 0x43b576 0x44b1d2 0x7785dd 0x46b861
#	0x7785dc	database/sql.(*DB).connectionCleaner+0xbc	/usr/local/go/src/database/sql/sql.go:1068
```

So, I just wanted to understand, what is the best way to use pooling with go_ibm_db?

**Comment by bimalkjha** [comment]
@kushaal-veijay Approach 1. Thanks.

**Comment by kushaal-veijay** [comment]
@bimalkjha, there are couple of problems that I see with approach 1.
1.  I see that even if we have only 100 connections in the pool, I see thousands of go routines waiting on go d.Timeout()
2. If the Psize gets larger by Poolsize, I see that we are making a new connection and returning that to the user. Is that correct understanding? If so, this means that the number of connection to database would exceed the pool size. Shouldn't we wait for the connection to be released back to the pool and then return the existing connection? This will ensure that the number of connection to the database never exceeds pool size.

Am I missing anything?

**Comment by vmathur12** [comment]
Hi @kushaal-veijay 
Yes, your understanding is correct. Just FYI:
The current Pooling implementation recommended by Go is as follows
Open new connections beforehand and kept in the available pool. As and when needed a client can request a connection from the available pool and it will move to used pool. When the application completes a transaction, it returns the connection to the available pool
PoolSize imposes a limit on the number of connections to server. SetConnMaxLifetime sets the maximum length of time a connection can be idle before it is closed.
When the number of connections go beyond PoolSize and a new connection is created directly using sql.open instead of pool.Open and this connection is will not be kept in used pool. This connection will close once the application completes a transaction and return to user.
Create all the connections beforehand and this will take time to create the connections.
Sure, we will look into your suggestion and check its plausibility based on our internal discussion. Please let me know If I made myself clear or you need any additional details.
Please share your testcases and repro steps for our information.
Thanks

**Comment by kushaal-veijay** [comment]
@vmathur12 Yes, what you described aligns to my understanding as well. But as you also pointed that we are not limiting the number of connection to the server based on the size of the pool, which may lead to issue in case server is restricting the number of connection. I will share the code which recreates this and share with you.

**Comment by vmathur12** [comment]
@kushaal-veijay  Please share the code which recreates this.

**Comment by vmathur12** [comment]
@kushaal-veijay  The current Pooling implementation recommended by Go. As of now, limiting the number of connection is not in our timeline. If any customer requests us for this support we will support it. Hence closing the issue.
