### ISSUE TITLE
Connection to Db2 is unstable

### ISSUE THREAD

**Issue by maxatcn** [ibmdb/go_ibm_db#167]
go_ibm_db version: 0.4.1
ODBC driver:  22nd March, 2022
Db2 version:    11.5.0.0 (dedicated db for this testing)

Dear team, we are in DV development. During the test, we found some performance issue.  After some of the testing, we narrow down the direction and found the connection to database is unstable(from Go code to Db2 or DV).

Let me add the test result, connecting to Db2 with Go  **VS** connection to Db2 with Java JDBC(running the same queries for 50 times and print out the time slip.)

With Java JDBC: (From the result,  except the first one, all the rest  is similar. That means it is stable.)
```
cost:3273   max:3273  min:3273
cost:1201   max:3273  min:1201
cost:1210   max:3273  min:1201
cost:1227   max:3273  min:1201
cost:1249   max:3273  min:1201
cost:1213   max:3273  min:1201
cost:1210   max:3273  min:1201
cost:1272   max:3273  min:1201
cost:1239   max:3273  min:1201
cost:1258   max:3273  min:1201
cost:1230   max:3273  min:1201
cost:1280   max:3273  min:1201
cost:1241   max:3273  min:1201
cost:1183   max:3273  min:1183
cost:1237   max:3273  min:1183
cost:1219   max:3273  min:1183
cost:1218   max:3273  min:1183
cost:1374   max:3273  min:1183
cost:1234   max:3273  min:1183
cost:1223   max:3273  min:1183
cost:1227   max:3273  min:1183
cost:1216   max:3273  min:1183
cost:1229   max:3273  min:1183
cost:1214   max:3273  min:1183
cost:1216   max:3273  min:1183
cost:1176   max:3273  min:1176
cost:1248   max:3273  min:1176
cost:1210   max:3273  min:1176
cost:1297   max:3273  min:1176
cost:1175   max:3273  min:1175
cost:1195   max:3273  min:1175
cost:1185   max:3273  min:1175
cost:1210   max:3273  min:1175
cost:1219   max:3273  min:1175
cost:1215   max:3273  min:1175
cost:1182   max:3273  min:1175
cost:1297   max:3273  min:1175
cost:1266   max:3273  min:1175
cost:1218   max:3273  min:1175
cost:1238   max:3273  min:1175
cost:1222   max:3273  min:1175
cost:1287   max:3273  min:1175
cost:1467   max:3273  min:1175
cost:1199   max:3273  min:1175
cost:1263   max:3273  min:1175
cost:1257   max:3273  min:1175
cost:1288   max:3273  min:1175
cost:1175   max:3273  min:1175
cost:1225   max:3273  min:1175
cost:1216   max:3273  min:1175
```

With Go +ODBC ,(Most of time, it costs the similar time slip, but there are 4 run which exceeds it, 13, 4, 4, 3.)
```
Start time: 04-25-2022 16:58:14
End time: 04-25-2022 16:58:27
--------------------------------------------------------------------- Diff Seconds: 13.110979
Start time: 04-25-2022 16:58:27
End time: 04-25-2022 16:58:31
--------------------------------------------------------------------- Diff Seconds: 3.990396
Start time: 04-25-2022 16:58:31
End time: 04-25-2022 16:58:33
--------------------------------------------------------------------- Diff Seconds: 1.474515
Start time: 04-25-2022 16:58:33
End time: 04-25-2022 16:58:34
--------------------------------------------------------------------- Diff Seconds: 1.499716
Start time: 04-25-2022 16:58:34
End time: 04-25-2022 16:58:36
--------------------------------------------------------------------- Diff Seconds: 1.462538
Start time: 04-25-2022 16:58:36
End time: 04-25-2022 16:58:37
--------------------------------------------------------------------- Diff Seconds: 1.528824
Start time: 04-25-2022 16:58:37
End time: 04-25-2022 16:58:38
--------------------------------------------------------------------- Diff Seconds: 1.381210
Start time: 04-25-2022 16:58:38
End time: 04-25-2022 16:58:40
--------------------------------------------------------------------- Diff Seconds: 1.469211
Start time: 04-25-2022 16:58:40
End time: 04-25-2022 16:58:41
--------------------------------------------------------------------- Diff Seconds: 1.530963
Start time: 04-25-2022 16:58:41
End time: 04-25-2022 16:58:43
--------------------------------------------------------------------- Diff Seconds: 1.431059
Start time: 04-25-2022 16:58:43
End time: 04-25-2022 16:58:44
--------------------------------------------------------------------- Diff Seconds: 1.539539
Start time: 04-25-2022 16:58:44
End time: 04-25-2022 16:58:46
--------------------------------------------------------------------- Diff Seconds: 1.506987
Start time: 04-25-2022 16:58:46
End time: 04-25-2022 16:58:50
--------------------------------------------------------------------- Diff Seconds: 4.034132
Start time: 04-25-2022 16:58:50
End time: 04-25-2022 16:58:52
--------------------------------------------------------------------- Diff Seconds: 1.595857
Start time: 04-25-2022 16:58:52
End time: 04-25-2022 16:58:53
--------------------------------------------------------------------- Diff Seconds: 1.604148
Start time: 04-25-2022 16:58:53
End time: 04-25-2022 16:58:55
--------------------------------------------------------------------- Diff Seconds: 1.602753
Start time: 04-25-2022 16:58:55
End time: 04-25-2022 16:58:56
--------------------------------------------------------------------- Diff Seconds: 1.438603
Start time: 04-25-2022 16:58:56
End time: 04-25-2022 16:58:58
--------------------------------------------------------------------- Diff Seconds: 1.499102
Start time: 04-25-2022 16:58:58
End time: 04-25-2022 16:58:59
--------------------------------------------------------------------- Diff Seconds: 1.416963
Start time: 04-25-2022 16:58:59
End time: 04-25-2022 16:59:01
--------------------------------------------------------------------- Diff Seconds: 1.383430
Start time: 04-25-2022 16:59:01
End time: 04-25-2022 16:59:02
--------------------------------------------------------------------- Diff Seconds: 1.388344
Start time: 04-25-2022 16:59:02
End time: 04-25-2022 16:59:03
--------------------------------------------------------------------- Diff Seconds: 1.436406
Start time: 04-25-2022 16:59:03
End time: 04-25-2022 16:59:05
--------------------------------------------------------------------- Diff Seconds: 1.464210
Start time: 04-25-2022 16:59:05
End time: 04-25-2022 16:59:06
--------------------------------------------------------------------- Diff Seconds: 1.612407
Start time: 04-25-2022 16:59:06
End time: 04-25-2022 16:59:08
--------------------------------------------------------------------- Diff Seconds: 1.376264
Start time: 04-25-2022 16:59:08
End time: 04-25-2022 16:59:09
--------------------------------------------------------------------- Diff Seconds: 1.391395
Start time: 04-25-2022 16:59:09
End time: 04-25-2022 16:59:11
--------------------------------------------------------------------- Diff Seconds: 1.417037
Start time: 04-25-2022 16:59:11
End time: 04-25-2022 16:59:14
--------------------------------------------------------------------- Diff Seconds: 3.127723
Start time: 04-25-2022 16:59:14
End time: 04-25-2022 16:59:15
--------------------------------------------------------------------- Diff Seconds: 1.393213
Start time: 04-25-2022 16:59:15
End time: 04-25-2022 16:59:17
--------------------------------------------------------------------- Diff Seconds: 1.870840
Start time: 04-25-2022 16:59:17
End time: 04-25-2022 16:59:18
--------------------------------------------------------------------- Diff Seconds: 1.398497
Start time: 04-25-2022 16:59:18
End time: 04-25-2022 16:59:20
--------------------------------------------------------------------- Diff Seconds: 1.467391
Start time: 04-25-2022 16:59:20
End time: 04-25-2022 16:59:21
--------------------------------------------------------------------- Diff Seconds: 1.358542
Start time: 04-25-2022 16:59:21
End time: 04-25-2022 16:59:23
--------------------------------------------------------------------- Diff Seconds: 1.378753
Start time: 04-25-2022 16:59:23
End time: 04-25-2022 16:59:24
--------------------------------------------------------------------- Diff Seconds: 1.403346
Start time: 04-25-2022 16:59:24
End time: 04-25-2022 16:59:26
--------------------------------------------------------------------- Diff Seconds: 1.488915
Start time: 04-25-2022 16:59:26
End time: 04-25-2022 16:59:27
--------------------------------------------------------------------- Diff Seconds: 1.373796
Start time: 04-25-2022 16:59:27
End time: 04-25-2022 16:59:28
--------------------------------------------------------------------- Diff Seconds: 1.509000
Start time: 04-25-2022 16:59:28
End time: 04-25-2022 16:59:30
--------------------------------------------------------------------- Diff Seconds: 1.380907
Start time: 04-25-2022 16:59:30
End time: 04-25-2022 16:59:31
--------------------------------------------------------------------- Diff Seconds: 1.394705
Start time: 04-25-2022 16:59:31
End time: 04-25-2022 16:59:33
--------------------------------------------------------------------- Diff Seconds: 1.380457
Start time: 04-25-2022 16:59:33
End time: 04-25-2022 16:59:34
--------------------------------------------------------------------- Diff Seconds: 1.386323
Start time: 04-25-2022 16:59:34
End time: 04-25-2022 16:59:35
--------------------------------------------------------------------- Diff Seconds: 1.344534
Start time: 04-25-2022 16:59:35
End time: 04-25-2022 16:59:37
--------------------------------------------------------------------- Diff Seconds: 1.376770
Start time: 04-25-2022 16:59:37
End time: 04-25-2022 16:59:38
--------------------------------------------------------------------- Diff Seconds: 1.454647
Start time: 04-25-2022 16:59:38
End time: 04-25-2022 16:59:40
--------------------------------------------------------------------- Diff Seconds: 1.430148
Start time: 04-25-2022 16:59:40
End time: 04-25-2022 16:59:41
--------------------------------------------------------------------- Diff Seconds: 1.439658
Start time: 04-25-2022 16:59:41
End time: 04-25-2022 16:59:42
--------------------------------------------------------------------- Diff Seconds: 1.466840
Start time: 04-25-2022 16:59:42
End time: 04-25-2022 16:59:44
--------------------------------------------------------------------- Diff Seconds: 1.462040
Start time: 04-25-2022 16:59:44
End time: 04-25-2022 16:59:46
--------------------------------------------------------------------- Diff Seconds: 1.622322
```

Is there any performance issue similar? Can you please have a check?

Let me add the Go code here,
```
for i := 0; i < 50; i++ {

		dt := time.Now()
		fmt.Println("Start time: " + dt.Format("01-02-2006 15:04:05"))

		stringArray := []string{"HOSTNAME=<db2 host>;PORT=50000;DATABASE=sample;UID=db2inst1;PWD=<passwd>"}
		con := utils.StringsBuilder(stringArray)

		db, err := sql.Open("go_ibm_db", con)
		if err != nil {
			log.Println(err)
		}
		defer db.Close()

		stringArray1 := []string{"select * from DB2INST1.EMPLOYEE"}
		sqlString := utils.BuildSQLQuery(stringArray1)

		st, err := db.Prepare(sqlString)
		if err != nil {
			log.Println(sqlString)
			log.Println(err.Error())
		}

		rows, err := st.Query()
		if err != nil {
			log.Println(err.Error())
		}

		defer rows.Close()
		rows.Close()
		st.Close()
		//db.Close()

		dt1 := time.Now()
		fmt.Println("End time: " + dt1.Format("01-02-2006 15:04:05"))

		diff := dt1.Sub(dt)
		fmt.Printf("--------------------------------------------------------------------- Diff Seconds: %f\n", diff.Seconds())

		if err != nil {
			t.Errorf("Error was not expected while insert the cache")
		}
	}
```

**Comment by vmathur12** [comment]
@maxatcn 
This is an expected behavior,each time a client attempts to access a backend service, it requires OS resources to create, maintain, and close connections to the datastore. The first actual connection to the datastore will be established lazily when it’s needed for the first time. 
 
I have tested the same code
 
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.544192
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.016237
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.016818
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.014400
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.013014
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.014706
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:32:32
-------------------------------------Diff Seconds: 0.014316
Start time: 05-03-2022 05:24:32
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.019621
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.014770
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013801
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.014369
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.016448
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015547
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015054
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013567
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013169
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013458
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.014131
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013247
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.013596
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015630
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015712
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.016482
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015937
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.014205
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.019722
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.016295
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.015891
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.029518
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.018827
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.022898
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.027947
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.029577
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.031202
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.028636
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.022679
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.029759
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.031902
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.033074
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.028055
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.033649
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.024509
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.032995
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.018650
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.026224
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.032376
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.024635
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.035480
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.029553
Start time: 05-03-2022 05:24:33
End time: 05-03-2022 05:33:33
-------------------------------------Diff Seconds: 0.018245

**Comment by maxatcn** [comment]
> Note: I am not a developer for this driver.
> 
> Some questions:
> 
>     * What is your test setup? Same machine or network hops?
> 
>     * It seems no SSL / TLS handshake, right?
> 
>     * What the database activated all the time?
> 
>     * What does "cost" for JDBC mean? What is min / max? I don't see any seconds (time)?

Yes, it was connecting to the same Db2 on same machine, with same network environment.  The difference looks JDBC connection is more stable than my Go program.

**Comment by data-henrik** [comment]
I asked about "cost" with JDBC and "time" for Go. What is cost, how was it determined? It looks to me as if you are not comparing the right things. Is cost the measured time or the estimated cost of the statement (some number)? 

Did you activate the database?

**Comment by maxatcn** [comment]
> I asked about "cost" with JDBC and "time" for Go. What is cost, how was it determined? It looks to me as if you are not comparing the right things. Is cost the measured time or the estimated cost of the statement (some number)?
> 
> Did you activate the database?

@data-henrik ,  what does it mean  'Did you activate the database?' ?

It is the time cost, before the sql sends out and after the result returned, print the current timestamp. And then the last one substract the previous one. 

Also,  I am not comparing the time cost between Java and Go.(It is not a Java VS Go, with Java and Go test result, it is just a reference).  It is time cost comparison with Java and Go. That is why 50 times run and each time cost printed.

**Comment by data-henrik** [comment]
@maxatcn If you do not know "activating the database", you probably do not have much experience with Db2 performance. See https://www.ibm.com/docs/en/db2/11.5?topic=commands-activate-database for the command.

**Comment by maxatcn** [comment]
@data-henrik,  the database is in full functional.  If there is performance issue in database, we don't know and that's  what we want to find out. 

From the application perspective, there is performance issue. For example the 50 times run,  the time cost is varies, and some is worse than others.  The code for 50 times run  is only for testing,  in our application test, some of the worst case, the time cost more than 12s. For a restful api call, it is really bad. 

Go code -> go_ibm_db -> ODBC driver-> Db2, this is the call chain.   We don't know what is the root cause for the issue, but go_ibm_db is the first place after the Go code. That is why I opened the ticket at first here.

**Comment by data-henrik** [comment]
To investigate performance issues, you start with the database setup and verify some configuration. The first: Is your database activated? To me it seems this is not the case or has not been verified.

I am not a developer, only a user of this Db2 driver. However, without that information this issue should be closed.

**Comment by maxatcn** [comment]
If the db2 running properly with Java,why you always want to check in Db2 side?  Any experience you could share in the similar issue?

**Comment by data-henrik** [comment]
Is it running properly with Java. Please share the recorded execution times, similar to those for the Go driver. I only see "costs", not seconds.

**Comment by maxatcn** [comment]
As I mentioned, Go code -> go_ibm_db -> ODBC driver-> Db2 , in this call chain,  I am not sure where is the root cause. Any information or proof I need to close this issue and get to Db2 directly?  I would like to report to Db2 if any information specify this is a Db2 issue. Can you please provide more  @data-henrik

**Comment by maxatcn** [comment]
> Is it running properly with Java??? Please share the recorded execution times, similar to those for the Go driver. I only see "costs", not seconds.

In the original description, it already paste the test with Java.  The same method with Go, print the 1st timestamp, after the sql run, print the 2nd timestamp, and the printed cost is the time cost.

**Comment by data-henrik** [comment]
@maxatcn Could you please post the timestamps and diffs for Java? I only see "costs". Costs have a different meaning in the context of Db2. Do you want to compare apples to apples?
> cost:3273   max:3273  min:3273
vs
> Diff Seconds: 0.028636

This is my last comment until you provide information about your Db2 setup and how you measured.

**Comment by maxatcn** [comment]
@data-henrik , what Db2 configuration you want to check?
You are running to a wrong direction I think. 
First, this is not a place to discuss Db2 performance issue, this is go_ibm_db.  Maybe finally  this is a database issue, we will discuss more in Db2 forum, not here.  I would like to hear 'this is not a driver issue, **because** XXXX'.

In the real case, it is more complex.  The original database is DV, not Db2.  We found the restful api performance bad, sometimes it costs more than 20s, sometime it is better 2-3s. There is the network impact , then we write Java and Go code to interact with database directly, to simplify the issue.  The Java and Go code run multiple times with DV, with Db2.
The result summarized: the Go code run with more peak(both run 50 times) than Java code(both in DV and Db2).

To simplify the issue, I did not add so complex environment info and how much test we have done on this. Also, you might not have a DV database, I only mentioned Db2 in the description.
If this is a Db2 performance issue only, I do not open a post here.

I hope you could understand.  Let's back to driver discussion here. If the unstable could be caused by driver?  If we are confident that this is not a driver issue, I will close it and check next.
