### ISSUE TITLE
Inconsistent GSKIT Error 2 

### ISSUE THREAD

**Issue by KC-Ogren** [ibmdb/go_ibm_db#207]
First request for a self signed SSL connection fails only sometimes. 

First request error:
SQLDriverConnect: {42724} [IBM][CLI Driver] SQL10013N  The specified library "GSKit Error: 2" could not be loaded.  SQLSTATE=42724

Subsequent request for same server:
SQLDriverConnect: {08001} [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "SSL".  Communication API being used: "SOCKETS".  Location where the error was detected: "SOCKETS".  Communication function detecting the error: "sqlccSSLSocketSetup".  Protocol specific error code(s): "414", "*", "*".  SQLSTATE=08001

I can navigate to the pem file and cat/view it and it looks the same as when it works.  

Restart container and try with the same server config and get no GSKIT error, connection works fine no issues for the rest of the life of the container. 

- os Version: ubi8
- cli-driver Version: v0.4.2
- Db2 Server Version: DB2 v11.5.8.0
- go Version: 1.20
<details><summary><code>go env</code> Output:</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/opt/app-root/src/.cache/go-build"
GOENV="/opt/app-root/src/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/opt/app-root/src/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/app-root/src/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.9"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/app/go.mod"
GOWORK=""
CGO_CFLAGS="-I/clidriver/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/clidriver/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build849116260=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

Steps to Reproduce:
Building container using dockerfile: 
FROM registry.access.redhat.com/ubi8/go-toolset:latest

Generate and persist the server certificate from TLS:
  certificate := tlsConn.ConnectionState().PeerCertificates[lastIndex].Raw
  pemPrivateBlock := &pem.Block{
	  Type:  "CERTIFICATE",
	  Bytes: certificate,
  }
  err = pem.Encode(pemPrivateFile, pemPrivateBlock)

Building connection string with something like this:
HOSTNAME=%s;DATABASE=%s;PORT=%s;UID=%s;PWD=%s;SECURITY=SSL;SSLSERVERCERTIFICATE=%s

SSLSERVERCERTIFICATE is the full path /x/y/hostname.pem
No spaces in the path.  

Some container starts everything works fine and some starts it gives GSKIT error 2?

**Comment by KC-Ogren** [comment]
Ok sure enough documenting this spotted a defer cancel() on the TLS context code that was likely running early.

Think it was just a race where it cancelled sometimes or completed depending on server response time.  The generated pem file looked ok, but maybe there was some missing end of file encoding that the cancel() interrupted the pem.Encode.

**Comment by KC-Ogren** [comment]
Seems to be 100% fine when launching the go app through ENTRYPOINT instead of a cmd:
#!/bin/bash
set -e

# Run before GO
db2cli validate

exec "./myapp"

**Comment by KC-Ogren** [comment]
Consistent gs kit 2 error:
Connect first time with a public signed certificate from a Db2 instance on ibm cloud.
With or without SSLSERVERCERTIFICATE populated, SECURITY=SSL.  


Waited between verifying cloud connect and self signed connection, so No timing / collisions issue.
  
Start self signed connection to DB2 SSL server fails with GS Kit 2 error.
Since it is self signed it requires SSLSERVERCERTIFICATE populated.

Reverse the order, so the first connection clidriver receives is self signed and it has no problem connecting to any other servers.  CA based or self signed.

**Comment by KC-Ogren** [comment]
Now that i can recreate consistently I tried to get into the error state and then try the clidriver directly.  

I can remote into the container that is giving 100% GS Kit errors and connect to the server using cli:
db2cli execsql -connstring x
It connects and runs commands without issue when the same connection string for sql.open fails on GSKit error.

**Comment by bimalkjha** [comment]
@KC-Ogren Please run below script and share complete output of script along with generated 1.* files:
```
#!/bin/bash
set -e

# Run before GO
db2cli validate
db2level
cd ...../clidriver/bin
db2trc on -f 1.trc
exec "./myapp"
db2trc off
db2trc fmt -cli 1.trc 1.cli
db2trc flw 1.trc 1.cli
db2trc fmt 1.trc 1.fmt
```
zip all generated 1.* files and share here. Also, let us know is it possible for you to install IBM Global Security Toolkit in the container or not. Thanks.

**Comment by bimalkjha** [comment]
@KC-Ogren I checked the trace files and it seems for second connection, clidriver is unable to add sslcertificate file in the inmemory keystore db and throwing error.
I tried to reproduce the error using cliscript but no luck so far! I have attached by test programs here.
Please download and save both files. Then edit it and update the first and second connection string as per your connection. Now, run these files using command `db2cli < ssl.txt` and `db2cli < ssl2.txt`. The ssl2.txt script will write output in db2cli.MT1 and db2cli.MT2 files. Please check these output to see if issue is reproducible in your env using these scripts and update here. Also, share your `myapp` program so that we can try to reproduce the issue using golang. Thanks.

[ssl.txt](https://github.com/ibmdb/go_ibm_db/files/11099732/ssl.txt)
[ssl2.txt](https://github.com/ibmdb/go_ibm_db/files/11099733/ssl2.txt)

**Comment by bimalkjha** [comment]
@KC-Ogren I am able to reproduce the issue using both ssl.txt and ssl2.txt now if both connection has different connection string with different certificate.
It is not the issue with go driver but problem with underlying IBM ODBC/CLI Driver used by ibm_db. You may have to open Case against IBM Support for this issue. Let me investigate more and then I'll put findings here. Thanks.

**Comment by bimalkjha** [comment]
@KC-Ogren I checked the repro test with different versions of clidriver. This bug got introduced in Db2 V11.5.5.0 and exists till V11.5.8.0 but seems fixed in latest code. I am unable to reproduce the problem using development branch code of Db2. So, this bug looks already fixed and in future version of clidriver, we can see the fix.
As of now, I would suggest you to download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/v11.5.4/linuxx64_odbc_cli.tar.gz, untar it and replace your `/opt/clidriver` with this clidriver. Then verify your test program and update here. It should work fine. Thanks.

**Comment by KC-Ogren** [comment]
Confirmed going back to 11.5.4 resolved the issue.

Where do I report clidriver issue?

**Comment by KC-Ogren** [comment]
I do not have access.  
Thank you for all the support.
